version: '3'
services:
  fanoverlord:
    image: ghcr.io/tomschlick/fanoverlord:latest
    container_name: fanoverlord
    environment:
      - IPMIHOST=${IPMIHOST}
      - IPMIUSER=${IPMIUSER}
      - IPMIPW=${IPMIPW}
      - SLEEP=${SLEEP}
    restart: always
    